#! /usr/bin/env fish

set branch (hg branch)
switch $argv[1]
case all
    set targets "own-linux-x86-64 pypy-c-jit-linux-x86-64"
case own
    set targets "own-linux-x86-64"
case jit
    set targets "pypy-c-jit-linux-x86-64"
case app
    set targets "pypy-c-app-level-linux-x86-64"
case '*'
    echo 'usage: $ bcheck [all,<target>]'
    exit 1
end

for target in $targets
   set result (curl -s -X POST --data \
            "forcescheduler=Force+Scheduler&username=plan_rich&reason=force+build&branch=$branch" http://buildbot.pypy.org/builders/$target/force)

    set url (echo $result | awk -F '[\']' '{gsub(/\.\.\//,"",$2); print $2}')

    echo "success => http://buildbot.pypy.org/$url"
end


